// Things sproutlings say. Short, soft, a little silly.
import { pick } from '../core/util.js';

export const LINES = {
  greet: ['hi!!', 'oh hi', 'hiii', 'hey friend', 'hello hello', 'good to see you!', '*waves*'],
  greetUser: ['oh! hi!!', "you're here!", 'hiii :)', 'hello, friend!', 'welcome back!', 'yay, company!'],
  chat: [
    'did you see the clouds?',
    'i fixed a thing!',
    'tea later?',
    'i had the best nap',
    'the plant grew a new leaf!!',
    'i have an idea…',
    'what if… sprinkles?',
    'i think the robot likes me',
    'the mail smells like adventure',
    'my sprout is extra perky today',
    'shh, i’m thinking',
    'have you tried the cookies',
    'i wrote a tiny poem',
    'we should build a rocket',
    'look, a dust bunny!',
    'i love this song',
  ],
  reply: ['hehe', 'ooh!', 'really?!', 'same!!', 'yesss', 'mhm mhm', 'wow', 'no way', 'tell me more', 'aww', 'heh, true'],
  work: ['almost there…', 'beep boop', 'hmm hmm', 'one more bolt…', 'it works!!', 'tiny progress!', 'clack clack'],
  idea: ['ooh, an idea!', 'what if…!', 'eureka!', 'i got it!'],
  sleepy: ['*yawn*', 'so sleepy…', 'nap time…', 'five more minutes…'],
  wake: ['huh? oh hi', 'mm… morning?', '*stretch*'],
  petted: ['hehe that tickles', 'mmmm', 'more pls', '♥', 'so nice…'],
  poked: ['eep!', 'boop!', 'hey!', 'hehe'],
  grumpy: ['hmph!', 'too many boops!', 'okay that’s enough'],
  held: ['wheee!', 'whoa!', 'put me down! (not yet)', 'i can see everything!'],
  dropped: ['oof', 'i’m okay!', 'again!!'],
  tripped: ['oops', 'i meant to do that', 'ow… i’m fine!'],
  noted: ['ooh, noted!', 'i’ll pin it up!', 'on the board it goes!', 'good one!!', 'writing it down!'],
  todo: ['added to the list!', 'got it, boss', 'on the board!', 'i’ll remember!'],
  love: ['♥♥♥', 'aww, love you too!', '*blushes*', 'you’re the best'],
  dance: ['dance party!!', 'woo!', 'let’s gooo', '♪♪♪'],
  bedtime: ['nighty night', 'okay… sleepy time', 'sweet dreams!'],
  morning: ['good morning!!', 'rise and shine!', 'is it morning?'],
  confused: ['hm?', 'i don’t get it but i love you', 'okay!', 'hehe what'],
  travel: ['off to the post room!', 'be right back', 'mail time!', 'brb'],
  mail: ['mail!!', 'stamp stamp', 'into the box you go', 'sending love'],
  bump: ['oops, sorry!', 'eep!', 'hehe bonk'],
};

export const line = (k) => pick(LINES[k] || LINES.reply);
